[general]
live_config_reload = true

[font]
size = 11.0
normal = { family = "Iosevka NFM", style = "Regular" }
italic = { family = "Iosevka NFM", style = "Italic" }
bold = { family = "Iosevka NFM", style = "Bold" }

[selection]
save_to_clipboard = true

[window]
decorations = "None"

